"""Initial schema

Revision ID: 244d81071cfe
Revises: 
Create Date: 2025-07-17 15:36:42.480507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '244d81071cfe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('student_country_code', sa.String(length=10), nullable=True),
    sa.Column('parent_country_code', sa.String(length=10), nullable=True),
    sa.Column('parent_name', sa.String(length=150), nullable=True),
    sa.Column('parent_email', sa.String(length=150), nullable=True),
    sa.Column('parent_phone', sa.String(length=50), nullable=True),
    sa.Column('discord_id', sa.String(length=100), nullable=True),
    sa.Column('sibling_reference', sa.String(length=150), nullable=True),
    sa.Column('learning_subject', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('fee_per_month', sa.Float(), nullable=False),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('residing_country', sa.String(length=50), nullable=True),
    sa.Column('reschedule_credits', sa.Integer(), nullable=True),
    sa.Column('date_joined', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('classes_per_week', sa.String(length=20), nullable=True),
    sa.Column('timezone', sa.String(length=10), nullable=True),
    sa.Column('class_time_raw', sa.Text(), nullable=True),
    sa.Column('zoom_link', sa.String(length=300), nullable=True),
    sa.Column('zoom_password', sa.String(length=100), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('grade', sa.String(length=50), nullable=True),
    sa.Column('school_name', sa.String(length=100), nullable=True),
    sa.Column('hobbies', sa.Text(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('future_college', sa.String(length=100), nullable=True),
    sa.Column('future_stream', sa.String(length=100), nullable=True),
    sa.Column('career_interest', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('attendance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment_statuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('month', sa.String(length=7), nullable=False),
    sa.Column('link_sent', sa.Boolean(), nullable=True),
    sa.Column('payment_done', sa.Boolean(), nullable=True),
    sa.Column('razorpay_payment_id', sa.String(length=100), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('month', sa.String(length=7), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('skipped_classes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('class_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('temporary_classes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('class_day', sa.String(length=20), nullable=False),
    sa.Column('class_time', sa.String(length=20), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('zoom_link', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_cancelled', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('temporary_classes')
    op.drop_table('student_comments')
    op.drop_table('skipped_classes')
    op.drop_table('payments')
    op.drop_table('payment_statuses')
    op.drop_table('attendance')
    op.drop_table('users')
    op.drop_table('students')
    # ### end Alembic commands ###
